# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Thineshkanth'
    subscriptionId: '81f0bd04-cb6d-4267-a768-e3d8f2ec475c'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Thineshkanth-RG'
    location: 'West US 2'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    csmParametersFile: 'azuredeploy.parameters.json'
    overrideParameters: 'adminPassword $(Thineshkanth)'
    deploymentMode: 'Incremental'
